# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

chisq_fix_reject <- function(design, n1, nuisance, type) {
    .Call('_blindrecalc_chisq_fix_reject', PACKAGE = 'blindrecalc', design, n1, nuisance, type)
}

chisq_recalc_reject <- function(design, n1, nuisance, type, nmat) {
    .Call('_blindrecalc_chisq_recalc_reject', PACKAGE = 'blindrecalc', design, n1, nuisance, type, nmat)
}

